server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: api-itemService
          uri: lb://API-ITEMSERVICE
          predicates:
            - Path=/api/items/**

        - id: api-payService
          uri: lb://API-PAYSERVICE
          predicates:
            - Path=/api/v1/payment/**

        - id: api-mailService
          uri: lb://API-USERSERVICE
          predicates:
            - Path=/api/mail/**

        - id: api-userService
          uri: lb://API-USERSERVICE
          predicates:
            - Path=/api/v1/member/**

        - id: api-loginService
          uri: lb://API-USERSERVICE
          predicates:
            - Path=/login/**
  main:
    web-application-type: reactive

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
