server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: api-itemService
          uri: lb://API-ITEMSERVICE
          predicates:
            - Path=/api/v1/items/**

        - id: api-payService
          uri: lb://API-PAYSERVICE
          predicates:
            - Path=/api/v1/payment/**
  main:
    web-application-type: reactive

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
