server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: api-memberService
          uri: lb://API-USERSERVICE
          predicates:
            - Path=/api/member/**

        - id: api-loginService
          uri: lb://API-USERSERVICE
          predicates:
            - Path=/login

        - id: api-mailService
          uri: lb://API-USERSERVICE
          predicates:
            - Path=/api/mail/**

        - id: api-activityService
          uri: lb://API-ACTIVITYSERVICE
          predicates:
            - Path=/api/activities/**

        - id: api-newsFeedService
          uri: lb://API-NEWSFEEDSERVICE
          predicates:
            - Path=/api/newsFeed/**
  main:
    web-application-type: reactive

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
